"""
Django settings for sky project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
#from decouple import config

#PAYPAL_MODE = 'sandbox'
#PAYPAL_CLIENT_ID='AR0tI0hOSG9hEFHKzm36mophmrE7iz4z5ZDT7YqKZVrbls8RK4oEsaU8kMwteTuEgA7XwU9BlCXBWvNc'
#PAYPAL_CLIENT_SECRET='ENm8By0p3XLh7vvlZcGPwi6Urtiz1_NxqL6jHH9_E2QkAGPhadHokoX23F-OKi0D9jfW8WzWxE_3nOwz'






# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fh+cour3ty4@g!2_=!peq8pav3@$rho!ofetsl-*on)o7ie$uq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'django_cron',
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'dbbackup',
    "django_apscheduler",
    'channels',
    
    'redis',
    'channels_rabbitmq',
    
]
ASGI_APPLICATION = 'sky.asgi.application'
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BASE_DIR/ 'backup'}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]
CRON_CLASSES = [
    'sky.cron.MyCronJob',
]

#CRONJOBS = [
   # ('*/1 * * * *', 'sky.cron.my_scheduled_job')
#]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "hosts": [("rabbitmq", 5672)],
            "userid": "guest",
            "password": "guest",
            "visibility_timeout": 3600,
        },
    },
}
ROOT_URLCONF = 'sky.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sky.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'skybackup',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '161616'
    },
    'second_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sky',
        'USER': 'root',
        'PASSWORD': '161616',
        'HOST': 'localhost'
        
    },
}
AUTH_USER_MODEL='store.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK={
    'DEFAULT_PERMISSION_CLASSES':(),
    'DEFAULT_AUTHENTICATION_CLASSES':(),
}
SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'store/templates/store/success.html'  # replace 'url-name' with the name of the URL to redirect to after login
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST =(
    'http://localhost:3000',
    'https://checkout.chapa.co/',
)
CORS_ALLOWED_ORIGIN_REGEXES = [
    "http://localhost:3000/*",  # Allow all paths from http://localhost:3000
]
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOWED_ORIGINS = [
    
    "http://localhost:3000",
    "http://127.0.0.1:9000",
    'https://checkout.chapa.co',
]
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'rpc://'

# Configure Celery to use Django settings
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
# Optional: Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
#9ade90dc-1570-4db5-a29e-867e4062fe3a
#res.setHeader("Access-Control-Allow-Origin", "*");
#dydi wcyw rvuv grjp
# settings.py

# Email configurations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # or 465 for SSL
EMAIL_USE_TLS = True  # TLS is required for Gmail
EMAIL_HOST_USER = 'ayelemintesnot77@gmail.com'  # SMTP username (your email address)
EMAIL_HOST_PASSWORD = 'ftfpuqxkmijpvhdt'  # SMTP password

# URL to the root of the website used in email ftfp uqxk mijp vhdt

# Other settings...
