# Generated by Django 4.2.6 on 2024-02-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_booking_bus_alter_users_phone_number_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_seats_booked',
            new_name='seat_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.AddField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bus'),
        ),
    ]
