# Generated by Django 4.2.6 on 2024-02-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_number_of_seats_booked_booking_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='travel_date',
        ),
    ]
