# Generated by Django 5.0.4 on 2024-05-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reating',
        ),
    ]
