# Generated by Django 4.2.6 on 2024-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
    ]
