# Generated by Django 4.2.6 on 2024-04-02 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_canclerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='canclerequest',
            name='Requested_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
