# Generated by Django 4.2.6 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_booking_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bus',
        ),
    ]
