# Generated by Django 5.0.4 on 2024-04-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_booking_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
