# Generated by Django 5.0.4 on 2024-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
